// Exact reference catalog and media slots. Production prices and statistics come from the API;
// reference price/rating/sold fields are also used by the isolated visual fixtures.
export const homeDesignProducts = [
  {
    name: "Nike Air Max 90",
    seller: "Nike Official",
    price: "125000",
    rating: "4.9",
    sold: "1.8K",
    image: "nike-air-max-90.jpg",
    background: "#f7f5f2",
  },
  {
    name: "Nike Club Hoodie",
    seller: "Nike Official",
    price: "78000",
    rating: "4.7",
    sold: "943",
    image: "nike-club-hoodie.jpg",
    background: "#f2f3f5",
  },
  {
    name: "iPhone 15 Pro",
    seller: "Jumia Nigeria",
    price: "1250000",
    rating: "4.9",
    sold: "2.1K",
    image: "iphone-15-pro.jpg",
    background: "#f0f5ff",
  },
  {
    name: "AirPods Pro 2",
    seller: "Jumia Nigeria",
    price: "320000",
    rating: "4.8",
    sold: "1.4K",
    image: "airpods-pro-2.jpg",
    background: "#f5f5f7",
  },
  {
    name: "Galaxy S25 Ultra",
    seller: "Samsung Store",
    price: "1690000",
    rating: "4.8",
    sold: "760",
    image: "galaxy-s25-ultra.jpg",
    background: "#f0f5ff",
  },
  {
    name: "Adidas Samba OG",
    seller: "Adidas Official",
    price: "145000",
    rating: "4.7",
    sold: "1.1K",
    image: "adidas-samba-og.jpg",
    background: "#f5f5f2",
  },
  {
    name: "MacBook Air M4",
    seller: "Apple Reseller",
    price: "2050000",
    rating: "4.9",
    sold: "540",
    image: "macbook-air-m4.png",
    background: "#eef5f3",
  },
  {
    name: "PS5 Slim Console",
    seller: "GameHub NG",
    price: "980000",
    rating: "4.8",
    sold: "890",
    image: "ps5-slim-console.png",
    background: "#f2f2f6",
  },
  {
    name: 'Hisense 55" 4K TV',
    seller: "Hisense Store",
    price: "620000",
    rating: "4.6",
    sold: "430",
    image: "hisense-55-4k-tv.png",
    background: "#eff6f7",
  },
  {
    name: "PowerBox 500",
    seller: "Oraimo Official",
    price: "48500",
    rating: "4.5",
    sold: "2.8K",
    image: "powerbox-500.jpg",
    background: "#f3f7ef",
  },
  {
    name: "Zara Linen Shirt",
    seller: "Zara Style",
    price: "42000",
    rating: "4.6",
    sold: "670",
    image: "zara-linen-shirt.png",
    background: "#f8f1ee",
  },
  {
    name: "JBL Flip 7",
    seller: "SoundCity NG",
    price: "185000",
    rating: "4.7",
    sold: "1.2K",
    image: "jbl-flip-7.png",
    background: "#f2f0f7",
  },
  {
    name: "Luxe 3-Seater Sofa",
    seller: "HomeStyle NG",
    price: "480000",
    rating: "4.7",
    sold: "215",
    image: "luxe-3-seater-sofa.png",
    background: "#f6f6f7",
  },
  {
    name: "Vitamin C Skincare",
    seller: "Glow Beauty",
    price: "36500",
    rating: "4.8",
    sold: "3.1K",
    image: "vitamin-c-skincare.jpg",
    background: "#f6f6f7",
  },
  {
    name: "Weekend Grocery",
    seller: "FreshMart NG",
    price: "28000",
    rating: "4.6",
    sold: "5.2K",
    image: "weekend-grocery.jpg",
    background: "#f6f6f7",
  },
  {
    name: "Adjustable Dumbbell",
    seller: "FitHouse NG",
    price: "95000",
    rating: "4.7",
    sold: "890",
    image: "adjustable-dumbbell.jpg",
    background: "#f6f6f7",
  },
] as const;
